### ISSUE TITLE
How to run my sequences with your code.

### ISSUE THREAD

**Issue by deepbrainme** [ppliuboy/SelFlow#1]
Hello Pengpeng Liu , I 'm very interested in your work. Is there a guide markdown for how to run your code .I 'm  fresh in tensorflow and will you release a pytorch-SelFlow in future?

**Comment by ppliuboy** [comment]
Hi, thanks for your interest! We will only release tensorflow code. For the guideline on running the code, we are preapring  and will release both training code and pre-trained models a few weeks later.
