### ISSUE TITLE
Phototmetric Loss Estimations 

### ISSUE THREAD

**Issue by VemburajYadav** [ppliuboy/SelFlow#11]
Under the five frame setting for Occlusion map estimation for three frame flow learning, could you please mention between which 2 sets of reference Image and its warped counterpart, the photometric loss is estimated  
1) I_t and [I_(t+1) warped by w_t_to_t+1]
2) I_t and [I_(t-1) warped by w_t_to_t-1]
3) I_(t+1) and [I_t warped by w_t+1_to_t]
4) I_(t-1) and [I_t warped by w_t-1_to_t]
5) I_(t+1) and [I_(t+2) warped by w_t+1_to_t+2]
6) I_(t+2) and [I_(t+1) warped by w_t+2_to_t+1]
7) I_(t-2) and [I_(t-1) warped by w_t-2_to_t-1]
8) I_(t-1) and [I_(t-2) warped by w_t-1_to_t-2]

Is it only summation of only 1 and 2 or 
(1+2+3+4) which also includes the symmetric backward counterparts of 1 and 2 or is it the summation of all 8 pairs.

Any suggestions would be really helpful.

**Comment by VemburajYadav** [comment]
Hi Penpeng,

Sorry for the mistake in the question. I realized that cases 5,6,7 and 8 are not possible because there are no occlusion maps for these cases. So, is it just 1+2 or (1+2+3+4)

**Comment by ppliuboy** [comment]
For the five-frame setting, you can apply photometric loss between I_t and I_(t-1), I_t and I_(t+1) i.e., (1+2+3+4), because you can compute occlusion maps between them.

**Comment by VemburajYadav** [comment]
Thank you very much for the info.
