### ISSUE TITLE
Where Census Transform happens?

### ISSUE THREAD

**Issue by coolbeam** [ppliuboy/SelFlow#12]
您好，我读了您的代码以及已经公开的无监督光流的代码，我都没有发现Census Transform这部分，请问，这一块是怎么做的呀，能透露一下吗

**Comment by ppliuboy** [comment]
目前这里只放了testing代码，如果需要training代码，可以先参考DDFlow：
https://github.com/ppliuboy/DDFlow/blob/master/ddflow_model.py#L131

**Comment by coolbeam** [comment]
> 目前这里只放了testing代码，如果需要training代码，可以先参考DDFlow：
> https://github.com/ppliuboy/DDFlow/blob/master/ddflow_model.py#L131

哇，太感谢了
