### ISSUE TITLE
Superpixel Generation

### ISSUE THREAD

**Issue by VemburajYadav** [ppliuboy/SelFlow#13]
Hi Pengpeng,

As it was referred in your paper that you had used the SLIC (Simple Linear Iterative Clustering) to generate superpixels for training your OCC model by self supervision, could you give me some info regarding the parameters of the SLIC algorithm, i.e (k=number of superpixels and m=compactness factor) that you used for KITTI and Sintel ?

**Comment by ppliuboy** [comment]
Hi,

During our experiments, we split one image into around 200 superpixels, and randomly select around 10 superpixels. Actually, you can choose other options.

Best
