### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by PyTorr** [ppliuboy/SelFlow#14]
How can I can train on my own dataset?
You reference to skimage, but I don;t see anywhere in the code that you data augmentation with superpixel, did I miss something?

**Comment by ppliuboy** [comment]
The superpixels are not enrolled in the training, instead, they are pre-computed before the second stage. I don't  write the code here, you can add it easily in the second stage as in DDFlow.

**Comment by PyTorr** [comment]
Thank you for the clarification.
