### ISSUE TITLE
Running model.test in a loop

### ISSUE THREAD

**Issue by ijazakhter** [ppliuboy/SelFlow#16]
Running model.test() in a loop gives variable scope error
Variable feature_extractor/conv1_1/weights already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope?

The error originates from line 11 of network.py 
net['conv1_1'] = slim.conv2d(x, 16, stride=2, scope='conv1_1')

**Comment by ppliuboy** [comment]
The error is that  some variables are defined more than once, but I have set [*reuse=True*](https://github.com/ppliuboy/SelFlow/blob/e55806fcda01810a502eea7bd73421b6ef27e4ce/network.py#L149) to avoid the issue. Please check your code again!
