### ISSUE TITLE
How to use DDFlow implementation to train SelFlow

### ISSUE THREAD

**Issue by Thomas-Mccabe** [ppliuboy/SelFlow#18]
Hi can you please provide more detail on how to train SelFlow. It is confusing in the readme. 

Any hep is appreciated!

**Comment by liuppboy** [comment]
See the reply from email.

**Comment by ppliuboy** [comment]
See the email reply.

**Comment by yuanxuanjing** [comment]
I have the same question with Thomas-Mccabe, can you give this email to me?

**Comment by yuanxuanjing** [comment]
I have the same question with Thomas-Mccabe, can you give this email to me? thank you so much! @ppliuboy @Thomas-Mccabe

**Comment by lhaippp** [comment]
Thanks for the excellent work!
------------------------------
BTW, could you please transfer the email to me? leefrancoch@gmail.com
Thanks in advance!

**Comment by komgyu** [comment]
> See the email reply.

Can I have more information about the training procedure? My email: komgyu96@gmail.com
I am especially interested in training the dance video you provided here. 
I think it will be also great if you can elaborate it in README so we can all take a look. 
Thank you!

**Comment by komgyu** [comment]
> Hi can you please provide more detail on how to train SelFlow. It is confusing in the readme.
> 
> Any hep is appreciated!

Can you please also transfer the email to me? Thank you!!! My email: komgyu96@gmail.com

**Comment by zfhxi** [comment]
> See the email reply.

Hi, Pengpeng Liu, Could you forward the email to zifeihanxi@hotmail.com? Thank you.
