### ISSUE TITLE
when do you release training code and models

### ISSUE THREAD

**Issue by swrdZWJ** [ppliuboy/SelFlow#2]

**Comment by ppliuboy** [comment]
August!

**Comment by FilippoAleotti** [comment]
Hi Pengpeng, thank you for sharing your code. Any news about the code for training your network?

**Comment by bywang2018** [comment]
@ppliuboy Hi Pengpeng, this job is great, when do you release the training code?

**Comment by Clear-fire** [comment]
Hi Pengpeng,thank you for your work, when do you release the training code?I can't wait for training for fun

**Comment by wanghao14** [comment]
@ppliuboy When would you like to release your training code? It is November now.

**Comment by ppliuboy** [comment]
See readme
