### ISSUE TITLE
Speed of generating flow

### ISSUE THREAD

**Issue by aoizoijoizj** [ppliuboy/SelFlow#20]
Hello,
I tested SelFlow in my server for 3 images (260px * 242px),
sometimes it takes more than 5 minutes for only this images, i don't know why, is it normal?

**Comment by ppliuboy** [comment]
No, it is not normal. In such a low-resolution, I think it shall taks less than 0.01s on a gpu.

**Comment by aoizoijoizj** [comment]
I've tested it in my web server and i think it doesn't have a gpu, should it take that long time if it doesn't have a gpu?

**Comment by aoizoijoizj** [comment]
And by the way, it's the most accurate library i've tried it for the optical flow. Thank you for your hard work.

**Comment by ppliuboy** [comment]
I shall be slower without using gpu. But it won't take so long time even on a cpu. I suggest you run a another device.

**Comment by aoizoijoizj** [comment]
Alright. Thank you so much!
