### ISSUE TITLE
Inference with only 2 frames

### ISSUE THREAD

**Issue by gcilli** [ppliuboy/SelFlow#21]
Hi, I am trying to run your code on the KITTI 2015 dataset. For each scene, it only provides two frames while, as far as I understand, your code requires three frames. I know that you also trained a two-frame version of Selflow, but could you please splecify which changes have to be made to the code such that it accept two frames?

Also, could you provide pretrained weights for the two-frames version on KITTI 2015?

Thank you.

**Comment by ppliuboy** [comment]
[DDFlow](https://github.com/ppliuboy/DDFlow) provides the two-frame implementation, and it also has unsupervised pre-trained models. For supervised pre-trained models, we will release it on another codebase.
