### ISSUE TITLE
how do you get the first frame prediction for sintel

### ISSUE THREAD

**Issue by lliuz** [ppliuboy/SelFlow#3]
Hi @ppliuboy
I'd like to know how your 3 frames model gets the optical flow for the first frame of sintel. It seems that your 3 frames model with input of frame 0, 1, 2 and predict the optical flow 10 and 12, which means that you can only get the flow of the first frame by input the frame -1, 0, 1. Is there any special for the first frame or we will just miss a sample for evaluation?

**Comment by ppliuboy** [comment]
We also train a two-frame version for Sintel, and use it to predict optical flow for the first frame. Our self-supervised learning technique is applicable to both two-frame and mult-frame formulation. In our experiments, three-frame version achieves slightly better results.

**Comment by lliuz** [comment]
Thanks for your reply. Have a nice day~
