### ISSUE TITLE
Doubt about the Superpixels computation

### ISSUE THREAD

**Issue by fperezgamonal** [ppliuboy/SelFlow#5]
Hello,

First of all, congratulations for your excellent work and results, I am currently finishing my MsC thesis and your work has been of great help.

In my thesis I do optical flow interpolation, not estimation and I am trying to use a similar idea to the occlusions hallucination but employ it to randomly sample the sparse flow given to the network, creating realistic holes (e.g.: regions where the flow was invalid because of occlusions, etc.) instead of simply using unrealistic rectangular regions.
In this regard, can you  tell me which superpixels (SLIC) implementation you used? In the past I used SLIC superpixels but if I'm not mistaken I used a C++ implementation with Matlab through MEX. I have searched for a Python implementation without success for now.

Finally, do you compute the superpixels "online" or create them somehow before training if the computation is slow?

Thanks in advance,

Cheers.
Ferran.

**Comment by ppliuboy** [comment]
Hi Ferran,

As for the superpixel implementation, there are several python packages, such as [skimage.segmentation.slic](https://scikit-image.org/docs/dev/api/skimage.segmentation.html#skimage.segmentation.slic). 

As for the training, it's okay to compute superpixels either online or offline. I just pre-compute superpixels offline to improve the efferciency.

**Comment by fperezgamonal** [comment]
Thanks @ppliuboy, I'll look into it!
