### ISSUE TITLE
About the speed

### ISSUE THREAD

**Issue by dagongji10** [ppliuboy/SelFlow#8]
Thanks for sharing the nice work!
I would like to ask the speed of the model and whether it can meet the real-time requirements.
When I use it for testing, it cost ~54ms for 256*340 frame. Is it normal?

**Comment by ppliuboy** [comment]
Yes, it is normal, because we do not fully optimize the model. It can be much faster after fully optimization, for example, you can choose to replace the cost volume part with implementation as in FlowNet.
