### ISSUE TITLE
Questions in ICCV 2019 paper

### ISSUE THREAD

**Issue by JohnnieXDU** [ppliuboy/SelFlow#9]
Hi Pengpeng, nice work about optical flow estimation. Here are some questions.

1. ![CodeCogsEqn](https://user-images.githubusercontent.com/29588335/68629645-888f3d80-04b2-11ea-9af3-27918626890f.gif) which described in Figure 2 notations can NOT be found in Figure 2. All the flow map shown in Figure 2 is w without head dot.  Same problem in Sec. 3.2.

2. No explaination about inital forward flow. Could you please explain it for readers?

**Comment by ppliuboy** [comment]
It represents the initial flow, which is obtained by bilinear upsampling from flow estimeted in previous level. Please check PWC-Net for details, our network structure is built upon it.
